POST http://localhost:3333/api/auth/register
Content-Type: application/json

{
  "email": "custom@customer.com",
  "password": "11111111",
  "role": "Performer",
  "firstname": "Andrey",
  "lastname": "Petrov",
  "dateBirth": "2000-01-01",
  "city": "Moscow"
}

###
POST http://localhost:3333/api/auth/login
Content-Type: application/json

{
  "email": "sASSDFAS",
  "password": "11111111"
}

###
POST http://localhost:3333/api/auth/refreshtoken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2E4YWE3MjcyYzQ5YjM5Y2U4NjE3ZjIiLCJlbWFpbCI6ImN1c3RvbWVyQGN1c3RvbWVyLmNvbSIsInJvbGUiOiJDdXN0b21lciIsImZpcnN0bmFtZSI6IjIyMjIyMjIyMiIsImxhc3RuYW1lIjpudWxsLCJhdXRoSWQiOiI2M2FkYzliZGZkOGU1NWYxNWFjZTIyMzEiLCJpYXQiOjE2NzIzMzM3NTcsImV4cCI6MTY3MjM0NDU1N30.sRta-iHyHfFMHQaF8KwKk694HJ9P808-W6jWCn2J93s

# {
#   "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2E4YWE3MjcyYzQ5YjM5Y2U4NjE3ZjIiLCJlbWFpbCI6ImN1c3RvbWVyQGN1c3RvbWVyLmNvbSIsInJvbGUiOiJDdXN0b21lciIsImZpcnN0bmFtZSI6IjIyMjIyMjIyMiIsImxhc3RuYW1lIjpudWxsLCJpYXQiOjE2NzIzMjM3MTAsImV4cCI6MTY3MjMzNDUxMH0.J9c7QoM9kQFJxP3kSKju75M_9iobnwcDTjG6BtOJpog"
# }

###
POST http://localhost:3333/api/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2E4YWE3MjcyYzQ5YjM5Y2U4NjE3ZjIiLCJlbWFpbCI6ImN1c3RvbWVyQGN1c3RvbWVyLmNvbSIsInJvbGUiOiJDdXN0b21lciIsImZpcnN0bmFtZSI6IjIyMjIyMjIyMiIsImxhc3RuYW1lIjpudWxsLCJhdXRoSWQiOiI2M2FkYzgyZWNlYjIyYzg3NjJiZjU2N2QiLCJpYXQiOjE2NzIzMzMzNTgsImV4cCI6MTY3MjM0NDE1OH0.gkzNZk_mdGWjywIIcuRmnOxOzpC09OkW6Qszvl4ED5k

###
PUT http://localhost:3333/api/user/63a599a135dbdf0fe0dd62a9/updatepassword
Content-Type: application/json

{
  "oldPassword": "11111111",
  "newPassword": "22222222"
}

###
PUT http://localhost:3333/api/user/63a8aa7272c49b39ce8617f2
Content-Type: application/json

{
  "firstname": "222222222",
  "specialization": ["IT"]
}

###
GET http://localhost:3000/api/user/63923e4bde079da10ffc0c90
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2M2E4YWE3MjcyYzQ5YjM5Y2U4NjE3ZjIiLCJlbWFpbCI6ImN1c3RvbWVyQGN1c3RvbWVyLmNvbSIsInJvbGUiOiJDdXN0b21lciIsImZpcnN0bmFtZSI6IjIyMjIyMjIyMiIsImxhc3RuYW1lIjpudWxsLCJhdXRoSWQiOiI2M2JjNTZkMmNiMjU0MjE1NTMxM2JhODMiLCJpYXQiOjE2NzMyODczNzgsImV4cCI6MTY3MzI4NzQzOH0.pg1Q9Ukf8zc-6o1hGPCMaITyx9B5-guJwSHy28OpadI

###
